import numpy as np
from numpy.typing import ArrayLike, NDArray

def codes_new_from_message(message: bytes) -> int: ...
def codes_grib_new_from_samples(sample: str) -> int: ...
def codes_get_long(gid: int, key: str) -> int: ...
def codes_get_double(gid: int, key: str) -> float: ...
def codes_get_values(gid: int) -> NDArray[np.float64]: ...
def codes_set_values(gid: int, values: ArrayLike) -> None: ...
def codes_get_message(gid: int) -> bytes: ...
def codes_release(gid: int) -> None: ...
